# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-29 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181029_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feautured',
            field=models.BooleanField(default=False),
        ),
    ]
